version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: ./node
    deploy:
      replicas: 3  # Scaling to 3 instances
    ports:
      - "3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "81:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
